In [1]:
import time
import pandas as pd
import requests
import json5

In [5]:
df = pd.read_csv("../Data/Employment_Projections.csv").sort_values('Employment 2030',ascending=False)

In [6]:
df.columns

Index(['Occupation Title', 'Occupation Code', 'Employment 2020',
       'Employment 2030', 'Employment Change, 2020-2030',
       'Employment Percent Change, 2020-2030',
       'Occupational Openings, 2020-2030 Annual Average',
       'Median Annual Wage 2020', 'Typical Entry-Level Education',
       'Education Code', 'Work Experience in a Related Occupation',
       'Workex Code', 'Typical on-the-job Training', 'trCode'],
      dtype='object')

In [8]:
df.head(10)

,Occupation Title,Occupation Code,Employment 2020,Employment 2030,"Employment Change, 2020-2030","Employment Percent Change, 2020-2030","Occupational Openings, 2020-2030 Annual Average",Median Annual Wage 2020,Typical Entry-Level Education,Education Code,Work Experience in a Related Occupation,Workex Code,Typical on-the-job Training,trCode
0,Home health and personal care aides,"=""31-1120""","3,470.7","4,600.6","1,129.9",32.6,599.8,"27,080",High school diploma or equivalent,7,None,4,Short-term on-the-job training,5
1,Fast food and counter workers,"=""35-3023""","3,455.5","3,973.0",517.5,15.0,804.6,"23,860",No formal educational credential,8,None,4,Short-term on-the-job training,5
2,Retail salespersons * Automotive Salesperso...,"=""41-2031""","3,835.0","3,795.7",-39.3,-1.0,524.5,"27,080",No formal educational credential,8,None,4,Short-term on-the-job training,5
3,Registered nurses * CCU Nurse* CNS* Clinica...,"=""29-1141""","3,080.1","3,356.8",276.8,9.0,194.5,"75,330",Bachelor's degree,3,None,4,None,6
4,"Laborers and freight, stock, and material move...","=""53-7062""","2,821.7","3,077.5",255.8,9.1,411.3,"31,120",No formal educational credential,8,None,4,Short-term on-the-job training,5
5,Cashiers * Cash Register Operator* Check Ou...,"=""41-2011""","3,379.1","3,042.7",-336.4,-10.0,546.9,"25,020",No formal educational credential,8,None,4,Short-term on-the-job training,5
6,Customer service representatives * Complain...,"=""43-4051""","2,923.4","2,888.8",-34.5,-1.2,361.7,"35,830",High school diploma or equivalent,7,None,4,Short-term on-the-job training,5
7,"Office clerks, general * Administrative Cle...","=""43-9061""","2,933.9","2,873.6",-60.4,-2.1,324.6,"35,330",High school diploma or equivalent,7,None,4,Short-term on-the-job training,5
8,General and operations managers * Departmen...,"=""11-1021""","2,411.9","2,638.2",226.3,9.4,229.6,"103,650",Bachelor's degree,3,5 years or more,1,None,6
9,Waiters and waitresses * Cocktail Server* C...,"=""35-3031""","2,023.2","2,430.7",407.6,20.1,470.2,"23,740",No formal educational credential,8,None,4,Short-term on-the-job training,5

In [9]:
df.columns

Index(['Occupation Title', 'Occupation Code', 'Employment 2020',
       'Employment 2030', 'Employment Change, 2020-2030',
       'Employment Percent Change, 2020-2030',
       'Occupational Openings, 2020-2030 Annual Average',
       'Median Annual Wage 2020', 'Typical Entry-Level Education',
       'Education Code', 'Work Experience in a Related Occupation',
       'Workex Code', 'Typical on-the-job Training', 'trCode'],
      dtype='object')

In [10]:
df[['Occupation Title','Employment 2030','Median Annual Wage 2020','Typical Entry-Level Education','Work Experience in a Related Occupation',
   'Typical on-the-job Training']].head(5)

,Occupation Title,Employment 2030,Median Annual Wage 2020,Typical Entry-Level Education,Work Experience in a Related Occupation,Typical on-the-job Training
0,Home health and personal care aides,"4,600.6","27,080",High school diploma or equivalent,None,Short-term on-the-job training
1,Fast food and counter workers,"3,973.0","23,860",No formal educational credential,None,Short-term on-the-job training
2,Retail salespersons * Automotive Salesperso...,"3,795.7","27,080",No formal educational credential,None,Short-term on-the-job training
3,Registered nurses * CCU Nurse* CNS* Clinica...,"3,356.8","75,330",Bachelor's degree,None,None
4,"Laborers and freight, stock, and material move...","3,077.5","31,120",No formal educational credential,None,Short-term on-the-job training